### PR TITLE
Scala 2.13 support

### PR DESCRIPTION
**Pull request by japgolly**
Waiting on https://github.com/scala/scala-collection-compat/issues/203

### CODE REVIEW

**Comment by nafg** [comment]
@japgolly sounds like it's released in 2.1.1 https://mvnrepository.com/artifact/org.scala-lang.modules/scala-collection-compat

**Comment by japgolly** [comment]
Yeah thanks, already upgraded; other problems :(

**Comment by nafg** [comment]
@japgolly anything interesting? ;)

**Comment by nafg** [comment]
> `[warn] 	:: org.scala-lang.modules#scala-collection-compat_sjs0.6_2.13;2.1.1: public: unable to get resource for org/scala-lang/modules#scala-collection-compat_sjs0.6_2.13;2.1.1: res=https://repo1.maven.org/maven2/org/scala-lang/modules/scala-collection-compat_sjs0.6_2.13/2.1.1/scala-collection-compat_sjs0.6_2.13-2.1.1.pom: java.net.SocketTimeoutException: connect timed out`

Travis has been having these hiccups lately... but otherwise :clap:

**Comment by japgolly** [comment]
> @japgolly anything interesting? ;)

@nafg no, just annoying unfortunately. But nearly there :)

**Comment by japgolly** [comment]
Finally! Will release now....

**Pull request merged**
